# Workflow နာမည်
name: Test V2Ray Keys and Upload to R2 & GitHub

on:
  schedule:
    # နာရီတိုင်း run မယ် (လိုအပ်သလို ပြင်ပါ)
    - cron: '0 * * * *'
  workflow_dispatch: # Manually run ခွင့်ပြုရန်

jobs:
  test-and-upload:
    runs-on: ubuntu-latest # Linux runner ကို သုံးမည်
    steps:
      # 1. Repository code ကို checkout လုပ်မည် (PUSH_TOKEN ကို အသုံးပြုရန်)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          persist-credentials: false # Credential conflict ရှောင်ရန်

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Python version (လိုအပ်လျှင် ပြင်ပါ)

      # 3. Install Python dependencies
      - name: Install Python dependencies
        run: pip install requests

      # 4. Download and Extract Xray
      - name: Download and Extract Xray
        run: python test_and_upload.py
        env:
          SOURCE_URLS_SECRET: ${{ secrets.SOURCE_URLS_SECRET }}

      - name: Give execute permission to Xray
        run: chmod +x ./xray

      # 6. Install rclone
      - name: Install rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      # 7. Configure rclone for Cloudflare R2
      - name: Configure rclone for Cloudflare R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: |
          rclone config create R2 s3 \
            provider=Cloudflare \
            access_key_id=$R2_ACCESS_KEY_ID \
            secret_access_key=$R2_SECRET_ACCESS_KEY \
            endpoint=$R2_ENDPOINT

      # 8. Upload working keys to R2 Bucket
      - name: Upload working keys to R2 Bucket
        env:
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: rclone copy working_keys.txt R2:${R2_BUCKET_NAME}/working_keys.txt --progress --verbose

      # 9. Clean up working keys file
      - name: Clean up working keys file
        run: rm working_keys.txt
        
