name: Test V2Ray Keys and Upload to R2

on:
  schedule:
    - cron: '*/15 * * * *' # Run every 15 minutes
  workflow_dispatch:

jobs:
  test-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install requests

      - name: Download and Extract Xray
        run: python test_and_upload.py
        env:
          SOURCE_URLS_SECRET: ${{ secrets.SOURCE_URLS_SECRET }}

      - name: Give execute permission to Xray
        run: chmod +x ./xray

      - name: Install rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Configure rclone for Cloudflare R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: |
          rclone config create R2 s3 \
            provider=Cloudflare \
            access_key_id=$R2_ACCESS_KEY_ID \
            secret_access_key=$R2_SECRET_ACCESS_KEY \
            endpoint=$R2_ENDPOINT

      - name: Upload working keys to R2
        env:
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: rclone copy working_keys.txt R2:${R2_BUCKET_NAME}/working_keys.txt --progress --verbose

      - name: Clean up working keys file
        run: rm working_keys.txt
