name: V2Ray Key Tester CI

on: schedule: - cron: '*/30 * * * *'  # Every 30 minutes

jobs: run-key-tester: runs-on: ubuntu-latest timeout-minutes: 10

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4
    with:
      token: ${{ secrets.PUSH_TOKEN }}

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'

  - name: Install Python Dependencies
    run: |
      python -m pip install --upgrade pip
      pip install requests

  - name: Run Key Tester Script
    env:
      SOURCE_URLS_SECRET: ${{ secrets.SOURCE_URLS_SECRET }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: python test_and_upload.py

  - name: Commit and Push Result
    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    run: |
      FILE="subscription/working_keys.txt"
      if [ -f "$FILE" ]; then
        git config --global user.name 'KeyBot'
        git config --global user.email 'keybot@users.noreply.github.com'
        git add "$FILE"
        git commit -m "Update working keys [CI Auto]"
        git push
      fi

